name: example
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  swidget:
    path: ../

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
